name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint black / isort

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black==21.5b0 isort==5.8.0

      - name: Run black
        run: |
          black --check --diff .

      - name: Run isort
        run: |
          isort --check-only .
